Update testPushCommit.yaml

diff --git a/.github/workflows/testPushCommit.yaml b/.github/workflows/testPushCommit.yaml
--- a/.github/workflows/testPushCommit.yaml
+++ b/.github/workflows/testPushCommit.yaml
@@ -4,10 +4,17 @@ on:
   pull_request:
 jobs:
   testPushCommit:
-    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.actor == 'renovate[bot]' && github.event.action == 'opened') }}
+    # if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.actor == 'renovate[bot]' && github.event.action == 'opened') }}
+    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.event.action == 'opened') }}
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
+      - name: Get PR info
+        id: get_pr_info
+        continue-on-error: false
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          echo "Actor from PR event: $GITHUB_ACTOR"
       - name: Get branch name
         id: get_branch_name
         continue-on-error: false
@@ -20,22 +27,22 @@ jobs:
             echo "Branch name from manual trigger: $GITHUB_REF_NAME"
             echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
           fi
-      - name: Fail if PR not matching expected branch
-        continue-on-error: false
-        if: ${{ !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'renovate-bot:renovate/gcp-libraries-bom.version') }}
-        run: |
-          echo "This workflow should only be auto-triggered from a renovate-bot branch to update libraries-bom"
-          echo "Stopping workflow triggered from branch: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
-          exit 1
-      - name: Test push new file
-        continue-on-error: false
-        run: |
-          echo "Hello world" > test.txt
-          
-          git config user.email "emmileaf@users.noreply.github.com"
-          git config user.name "Emily Wang"
-          
-          git checkout $BRANCH_NAME
-          git add test.txt
-          git commit -m "test: add file"
-          git push --set-upstream origin $BRANCH_NAME
+#      - name: Fail if PR not matching expected branch
+#        continue-on-error: false
+#        if: ${{ !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'renovate-bot:renovate/gcp-libraries-bom.version') }}
+#        run: |
+#          echo "This workflow should only be auto-triggered from a renovate-bot branch to update libraries-bom"
+#          echo "Stopping workflow triggered from branch: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
+#          exit 1
+#      - name: Test push new file
+#        continue-on-error: false
+#        run: |
+#          echo "Hello world" > test.txt
+#
+#          git config user.email "emmileaf@users.noreply.github.com"
+#          git config user.name "Emily Wang"
+#
+#          git checkout $BRANCH_NAME
+#          git add test.txt
+#          git commit -m "test: add file"
+#          git push --set-upstream origin $BRANCH_NAME
