Test with workflow_dispatch trigger instead

diff --git a/.github/workflows/testPushCommit.yaml b/.github/workflows/testPushCommit.yaml
--- a/.github/workflows/testPushCommit.yaml
+++ b/.github/workflows/testPushCommit.yaml
@@ -1,44 +1,65 @@
 name: Test Action
 on:
   workflow_dispatch:
-  pull_request:
+    inputs:
+      branch_name:
+        description: name of branch to push update commit to
+        required: true
+        default: "renovate/gcp-libraries-bom.version"
+      forked_repo:
+        description: full repo name if branch is in forked repo
+        required: false
+        default: "renovate-bot/emmileaf-_-tidbits"
+
 jobs:
   testPushCommit:
-    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.actor == 'renovate-bot' && github.event.action == 'opened') }}
+    # if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.actor == 'renovate-bot' && github.event.action == 'opened') }}
     # if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.event.action == 'opened') }}
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
-      - name: Get PR info
-        id: get_pr_info
-        continue-on-error: false
-        if: ${{ github.event_name == 'pull_request' }}
-        run: |
-          echo "Actor from PR event: $GITHUB_ACTOR"
-          echo "PR head repo full name: $HEAD_REPO_NAME"
-          echo "PR base repo full name: $BASE_REPO_NAME"
-        env:
-          HEAD_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
-          BASE_REPO_NAME: ${{ github.event.pull_request.base.repo.full_name }}
-      - name: Get branch name
-        id: get_branch_name
+#      - name: Get PR info
+#        id: get_pr_info
+#        continue-on-error: false
+#        if: ${{ github.event_name == 'pull_request' }}
+#        run: |
+#          echo "Actor from PR event: $GITHUB_ACTOR"
+#          echo "PR head repo full name: $HEAD_REPO_NAME"
+#          echo "PR base repo full name: $BASE_REPO_NAME"
+#        env:
+#          HEAD_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
+#          BASE_REPO_NAME: ${{ github.event.pull_request.base.repo.full_name }}
+#      - name: Get branch name
+#        id: get_branch_name
+#        continue-on-error: false
+#        run: |
+#          set -x
+#          if ${{ github.event_name == 'pull_request' }}; then
+#            echo "Branch name from PR event: $GITHUB_HEAD_REF"
+#            echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
+#          else
+#            echo "Branch name from manual trigger: ${{ github.event.inputs.branch_name }}"
+#            echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
+#          fi
+#      - name: Fail if PR not matching expected branch
+#        continue-on-error: false
+#        if: ${{ !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'renovate/gcp-libraries-bom.version') }}
+#        run: |
+#          echo "This workflow should only be triggered from a renovate-bot branch to update libraries-bom"
+#          echo "Stopping workflow triggered from branch: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
+#          exit 1
+      - name: Get libraries bom version
         continue-on-error: false
         run: |
           set -x
-          if ${{ github.event_name == 'pull_request' }}; then
-            echo "Branch name from PR event: $GITHUB_HEAD_REF"
-            echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
-          else
-            echo "Branch name from manual trigger: $GITHUB_REF_NAME"
-            echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
+          if ${{ github.event.inputs.forked_repo != '' }}; then
+            git fetch https://github.com/${{ github.event.inputs.forked_repo }}.git ${{ github.event.inputs.branch_name }}
+            git checkout FETCH_HEAD -- dependency-update-test/pom.xml
+          else 
+            git checkout ${{ github.event.inputs.branch_name }} -- dependency-update-test/pom.xml
           fi
-      - name: Fail if PR not matching expected branch
-        continue-on-error: false
-        if: ${{ !startsWith(steps.get_branch_name.outputs.BRANCH_NAME, 'renovate/gcp-libraries-bom.version') }}
-        run: |
-          echo "This workflow should only be triggered from a renovate-bot branch to update libraries-bom"
-          echo "Stopping workflow triggered from branch: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
-          exit 1
+          echo "LIBRARIES_BOM_VERSION=$(xmllint --xpath "string(//*[local-name()='gcp-libraries-bom.version'])" dependency-update-test/pom.xml)" >> $GITHUB_OUTPUT
+          echo "Libraries BOM version: ${LIBRARIES_BOM_VERSION}"
       - name: Test push new file
         continue-on-error: false
         run: |
@@ -49,19 +70,17 @@ jobs:
           git config user.email "emmileaf@users.noreply.github.com"
           git config user.name "Emily Wang"
 
-          if ${{ (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.fork) }}; then
-            git fetch $RENOVATE_FORK $BRANCH_NAME
+          if ${{ github.event.inputs.forked_repo != '' }}; then
+            git fetch https://github.com/${{ github.event.inputs.forked_repo }}.git ${{ github.event.inputs.branch_name }}
             git checkout FETCH_HEAD
             git stash pop
             git add test.txt
             git commit -m "test: add file"
-            git push $RENOVATE_FORK HEAD:${BRANCH_NAME}
+            git push https://github.com/${{ github.event.inputs.forked_repo }}.git HEAD:${{ github.event.inputs.branch_name }}
           else
-            git checkout $BRANCH_NAME
+            git checkout ${{ github.event.inputs.branch_name }}
             git stash pop
             git add test.txt
             git commit -m "test: add file"
-            git push -u origin $BRANCH_NAME
+            git push -u origin ${{ github.event.inputs.branch_name }}
           fi
-        env:
-          RENOVATE_FORK: "https://github.com/renovate-bot/emmileaf-_-tidbits.git"
